DROP TABLE IF EXISTS maps CASCADE;
DROP TABLE IF EXISTS points_of_interest CASCADE;
DROP TABLE IF EXISTS users_maps CASCADE;

CREATE TABLE maps (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  creator_id REFERENCES INTEGER users(id) ON DELETE CASCADE
);

CREATE TABLE points_of_interest (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255),
  map_id REFERENCES INTEGER maps(id) ON DELETE CASCADE
);

CREATE TABLE users_maps (
  id SERIAL PRIMARY KEY NOT NULL,
  saved_from_map_id REFERENCES INTEGER maps(id) ON DELETE CASCADE,
  saved_to_user_id REFERENCES INTEGER users(id) ON DELETE CASCADE
);